service: practica-aws

provider: ${file(./iac/provider.yml)}

custom:
  stage: ${sls:stage}
  awsRegion: ${env:AWS_REGION, 'us-east-1'}
  dynamodbTableName: ${env:DYNAMODB_TABLE_NAME, 'TransaccionesBancariasDev'}
  s3BucketName: ${env:S3_BUCKET_NAME, 'transacciones-reportes-303040220363'}
  logLevel: ${env:LOG_LEVEL, 'info'}

functions:
  registerPayment: ${file(./iac/functions/register-payment.yml)}
  getTransaction: ${file(./iac/functions/get-transaction.yml)}
  generateDailyReport: ${file(./iac/functions/generate-daily-report.yml)}

resources:
  Resources:
    TransaccionesTable: ${file(./iac/resources/dynamodb-table.yml)}
    ReportesBucket: ${file(./iac/resources/report-bucket.yml)}

plugins:
  - serverless-offline